spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: urstory
    password: u1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: blogpjt_f
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**

server:
  port: 9999

logging:
  level:
    org.springframework: INFO
    com.example.blog: DEBUG
